name: "🖥 :) ALL Tests : Execution"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1-5" # Every weekday
  push:
    branches:
      - main

permissions:
  contents: write

env:
  NODE_VERSION: "20"
  FEATURE: "all"
  ALLURE_VERSION: "2.19.0"
  EXECUTE_TYPE: "CI"

concurrency:
  group: environment-${{ github.ref }}-os
  cancel-in-progress: true

jobs:
  run-e2e-tests:
    runs-on: ubuntu-22.04
    name: "🕹️ Run E2E tests"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # important pour l'historique git

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps

      - name: Run tests
        run: npm run test:smoke

      # 👉 Récupération de l’historique Allure
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages-all
          path: gh-pages-all

      # 👉 Génération report + injection history
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure
        continue-on-error: true
        with:
          allure_results: report/allure-results
          allure_history: gh-pages-all
          allure_report: allure-report
          keep_reports: 20

      # 👉 Publication GitHub Pages (historique conservé)
      - name: Deploy Allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-all
          publish_dir: allure-report
          keep_files: true
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
          commit_message: "Update Allure report"